/*
 * This source file was generated by the Gradle 'init' task
 */
package heroengine;

import heroengine.ecs.Entity;
import heroengine.ecs.EntityManager;
import heroengine.components.Transform;
import heroengine.components.Sprite;
import org.junit.jupiter.api.Test;

import java.awt.Color;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void testEntityCreation() {
        EntityManager entityManager = new EntityManager();
        Entity entity = entityManager.spawn();
        assertNotNull(entity);
        assertTrue(entity.isActive());
    }

    @Test
    void testComponentAddAndGet() {
        Entity entity = new Entity();
        Transform transform = new Transform(100, 200);
        entity.addComponents(transform);

        assertTrue(entity.hasComponent(Transform.class));
        assertEquals(100, entity.getComponent(Transform.class).get().x);
        assertEquals(200, entity.getComponent(Transform.class).get().y);
    }

    @Test
    void testEntityManagerFiltering() {
        EntityManager entityManager = new EntityManager();

        entityManager.spawn(
                new Transform(0, 0),
                new Sprite(10, 10, Color.RED)
        );

        entityManager.spawn(
                new Transform(0, 0)
        );

        entityManager.refresh();

        assertEquals(2, entityManager.getEntities().size());
        assertEquals(1, entityManager.getEntitiesWith(Transform.class, Sprite.class).size());
    }
}
